language: bash

sudo: false

services:
  - docker
  
cache:
  - apt

before_install:
  - docker build -t debian-phantomjs .

script:
  - docker cp debian-phantomjs:/usr/bin/phantomjs phantomjs 

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file: "phantomjs"
  skip_cleanup: true
  on:
    tags: true
  
# after_deploy:
#  - push to docker hub?